
---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietPoC

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 11 * * 6'

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: preZero Scan
      run: |
        docker run --platform linux/amd64 --rm -t \
        --name slcore \ 
        -e SHIFTLEFT_ACCESS_TOKEN="$SHIFTLEFT_ACCESS_TOKEN" \
        -v $PWD:/app \
        -v /tmp:/tmp \
        shiftleft/core:latest \
        sl analyze --verbose --app javadockerscan --verbose  /app
